# =========================
# Database (prod)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# pool (recomendado)
spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:10}
spring.datasource.hikari.minimum-idle=${DB_POOL_MIN:2}

# =========================
# Flyway
# =========================
spring.flyway.enabled=true

# =========================
# AWS / SQS (prod)
# =========================
spring.cloud.aws.region.static=${SPRING_CLOUD_AWS_REGION_STATIC:sa-east-1}

# IAM Role / env vars
app.sqs.order-events-queue=${APP_SQS_ORDER_EVENTS_QUEUE:orderflow-order-events}

# Listener tuning (prod costuma ser mais conservador)
spring.cloud.aws.sqs.listener.max-messages-per-poll=${SQS_MAX_MESSAGES_PER_POLL:5}
spring.cloud.aws.sqs.listener.max-concurrent-messages=${SQS_MAX_CONCURRENT_MESSAGES:5}
spring.cloud.aws.sqs.listener.poll-timeout=${SQS_POLL_TIMEOUT:20s}
spring.cloud.aws.sqs.listener.acknowledgement-mode=ON_SUCCESS

# =========================
# Logging (prod)
# =========================
logging.level.com.dev01.orderflow.orderapi.infra.events=INFO
logging.level.io.awspring.cloud.sqs=WARN
logging.level.io.awspring.cloud.sqs.listener=WARN