# =========================
# Database (local)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/orderflow
spring.datasource.username=orderflow
spring.datasource.password=orderflow

# ==============================
# logs uteis de SQL em local
# ==============================
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# =========================
# AWS / SQS (local)
# =========================
spring.cloud.aws.region.static=${SPRING_CLOUD_AWS_REGION_STATIC:sa-east-1}
spring.cloud.aws.credentials.profile.name=${SPRING_CLOUD_AWS_CREDENTIALS_PROFILE_NAME:default}

# use URL (evita depender de list/getQueueUrl)
app.events.publisher=log
app.sqs.consumer.enabled=true
app.sqs.order-events-queue=${APP_SQS_ORDER_EVENTS_QUEUE:orderflow-order-events}

# =========================
# SQS listener tuning
# =========================
spring.cloud.aws.sqs.listener.max-messages-per-poll=5
spring.cloud.aws.sqs.listener.max-concurrent-messages=5
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.sqs.listener.acknowledgement-mode=ON_SUCCESS

# =========================
# Logging (local)
# =========================
logging.level.com.dev01.orderflow.orderapi.infra.events=INFO
logging.level.io.awspring.cloud.sqs=INFO
logging.level.io.awspring.cloud.sqs.listener=INFO

# ==========================
# actuator prometheus
# ==========================

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always