# =========================
# Database (dev)
# =========================
spring.datasource.url=jdbc:postgresql://<DEV_HOST>:5432/orderflow
spring.datasource.username=orderflow
spring.datasource.password=<DEV_PASSWORD>

# =========================
# Flyway
# =========================
spring.flyway.enabled=true

# =========================
# AWS / SQS (dev)
# =========================
spring.cloud.aws.region.static=${AWS_REGION:sa-east-1}
# em DEV ideal e IAM Role/Env vars, mas se for profile:
# spring.cloud.aws.credentials.profile.name=dev

app.events.publisher=sqs
app.sqs.consumer.enabled=true
app.sqs.order-events-queue=https://sqs.sa-east-1.amazonaws.com/696191863254/orderflow-order-events

# Listener tuning (pode ajustar)
spring.cloud.aws.sqs.listener.max-messages-per-poll=5
spring.cloud.aws.sqs.listener.max-concurrent-messages=5
spring.cloud.aws.sqs.listener.poll-timeout=20s
spring.cloud.aws.sqs.listener.acknowledgement-mode=ON_SUCCESS

# =========================
# Logging (dev)
# =========================
logging.level.com.dev01.orderflow.orderapi.infra.events=INFO
logging.level.io.awspring.cloud.sqs=INFO
logging.level.io.awspring.cloud.sqs.listener=INFO