server.port=8080

spring.jpa.open-in-view=false

spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.credentials.profile.name=default
app.sqs.order-events-queue=orderflow-order-events
logging.level.io.awspring.cloud.sqs=INFO
logging.level.com.dev01.orderflow.orderapi.infra.events=INFO

